domain: amca-qt.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://amca-qt.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: https://github.com/Amca-qt/amca-qt.github.io      # place folder name if the site is served in a subfolder
